CREATE DATABASE order_schema;

---For Salesman
CREATE TABLE SALESMAN
(SALESMANID NUMBER(4),
NAME VARCHAR(20),
CITY VARCHAR(20),
COMMISSION VARCHAR(20),
PRIMARY KEY (SALESMANID));

---For Customer
CREATE TABLE CUSTOMER
(CUSTOMERID NUMBER(4),
CUSTNAME VARCHAR(20),
CITY VARCHAR(20),
GRADE NUMBER(3),
PRIMARY KEY (CUSTOMERID),
SALESMANID REFERENCES SALESMAN(SALESMANID) ON DELETE SET NULL);

---For Orders
CREATE TABLE ORDERS
(ORDNO NUMBER(5),
PURCHASEAMT NUMBER(10,2),
ORDDATE DATE,
PRIMARY KEY(ORDNO),
CUSTOMERID REFERENCES CUSTOMER(CUSTOMERID)ON DELETE CASCADE,
SALESMANID REFERENCES SALESMAN(SALESMANID) ON DELETE SET NULL);