CREATE DATABASE order_schema;

---For Salesman
CREATE TABLE SALESMAN
(SALESMANID INT(4),
NAME VARCHAR(20),
CITY VARCHAR(20),
COMMISSION VARCHAR(20),
PRIMARY KEY (SALESMANID));

---For Customer
CREATE TABLE CUSTOMER
(CUSTOMERID INT(4),
CUSTNAME VARCHAR(20),
CITY VARCHAR(20),
GRADE INT,
SALESMANID INT,
PRIMARY KEY (CUSTOMERID),
FOREIGN KEY (SALESMANID) REFERENCES salesman(SALESMANID) ON DELETE SET NULL);

---For Orders
CREATE TABLE ORDERS 
(ORDNO INT, 
PURCHASEAMT FLOAT(10,2), 
ORDDATE DATE, 
CUSTOMERID INT, 
SALESMANID INT, 
PRIMARY KEY(ORDNO), 
FOREIGN KEY (CUSTOMERID) REFERENCES CUSTOMER(CUSTOMERID) ON DELETE CASCADE, 
FOREIGN KEY (SALESMANID) REFERENCES SALESMAN(SALESMANID) ON DELETE CASCADE);